<%@ Page Language="VB" AutoEventWireup="false" CodeFile="iformapago.aspx.vb" Inherits="iformapago" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<link href="FormaPago_files/perutourism.css" rel="stylesheet" type="text/css" />
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>PeruTourism</title>
    <style type="text/css">
        .style1
        {
            height: 110px;
        }
        .style2
        {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 14px;
            color: #444445;
            text-decoration: none;
            width: 484px;
        }
    </style>
</head>
<body bgcolor="#FFFFFF" text="#000000" link="#32651C" vlink="#32651C" alink="#32651C">
    <form id="form1" runat="server">
    <div>

<table width="500" height="410" border="0" style="border:black 1px solid" align="center" cellpadding="0" cellspacing="0">
  <tbody>
  <tr>
	<td colspan="3" class="style1"><img style="margin:-9px 0px 0px 1px" 
            src="./FormaPago_files/mini_top.gif" width="497" height="70" border="0" 
            usemap="#Map"></td>
  </tr>
  
  <tr>
    <td colspan="3"><img src="./FormaPago_files/circulo_verde.gif" width="34" height="33" align="absmiddle">&nbsp;<span class="titulo_verde">Payment Procedure
    </span></td>
  </tr>
  
  <tr>
    <td width="5" ></td>
    <td valign="top" class="style2"><p align="justify">
        <span style="color: rgb(68, 68, 69); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 19.8799991607666px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">
        To confirm your trip we just need a deposit of the 30%, this first payment can 
        be done online through your personalized website only if you have a Visa card or 
        Master card, if you have American Express card I will send you our services 
        agreement by email.</span></p>
    
    <p align="justify">
        <span style="color: rgb(68, 68, 69); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 19.8799991607666px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">
        The balance due (70%) must be paid at your arrival in Lima.</span></p>
    <p style="height: 2px"></p>
   
    </td>
    <td width="5" ></td>
  </tr>
  
   <tr>
    <td colspan="3"><img src="./FormaPago_files/circulo_verde.gif" width="34" height="33" align="absmiddle">&nbsp;<span class="titulo_verde">Our Cancellation Policy
    </span></td>
  </tr>
  
 
  <tr>
    <td width="5" ></td>
    <td valign="top" class="style2"><p align="justify">Fully acquit you of all cost (*) that may be generated by the cancellation of the services already booked by Perutourism according to the itinerary in case you cancel the services up to 45 days before  your arrival.</p>
    
    <p align="justify">
(*) Valid only for parties not larger than six (06) people.<br />
(*) Valid for every destination throughout Peru.<br />
(*) The Inca Trail is not included in this Cancelation policy.<br />
(*) The Amazon cruises are not included in this Cancelation policy.<br />
(*) Valid for cancellations 45 days before your arrival.<br />
(*) The domestic or international air tickets are not included in this Cancelation Policy.<br /> 
(*) The amount to be refunded will have a charge of $50 per passenger.
</p>
<p style="height: 2px"></p>
    </td>
    <td width="5" ></td>
  </tr>


  <tr>
    <td width="5" ></td>
    <td valign="top" class="style2">
    <p align="justify" ><b>Our cancellations after this term:</b><br />
    The penalty will be 50% of the tour. Customer will accept credit card debiting or other payment method.
</p>
<p style="height: 2px"></p>
      
    <td width="5" ></td>
  </tr>


  <tr>
    <td width="5" ></td>
    <td valign="top" class="style2">
    
    <p align="justify" ><b>Our Cancellation Policy after the arrival:</b><br />
    If the customer cancels part or all services after the beginning of the Tour, it will be charged with not less than 100% of agreed total price of Tour.
</p>
<p style="height: 2px"></p>
      
    </td>
    <td width="5" ></td>
  </tr>


  <tr>
    <td width="5" ></td>
    <td valign="top" class="style2">
    
    <p align="justify" ><i>
    PERUTOURISM is not liable to assume any charges in case of unexpected events beyond our control but we will assist you until problem will be solved.
    </i>
    </p>
<p style="height: 5px"></p>
      
    </td>
    <td width="5" ></td>
  </tr>





  
  
  <tr>
    <td colspan="3" valign="bottom" class="pie"><div align="center">Please let us know your comments <a href="mailto:peru@perutourism.com">peru@perutourism.com</a>.<br>
      
Av. Larco 101, Suite 1301, Miraflores, Lima, Peru. Phone: (51 1) 241-4724 Fax: (51 1) 444-0015</div></td>
  </tr>
</tbody></table>
<map name="Map" id="Map"><area shape="rect" coords="444,22,497,39" href="javascript:window.close()">
</map>
<script src="./FormaPago_files/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
    _uacct = "UA-2723415-1";
    urchinTracker();
</script>



    
    </div>
    </form>
</body>
</html>
